apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: blackstark2099/event-bus
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  type: ClusterIP 
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-node-port-srv
spec:
  type: NodePort 
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 5000
      targetPort: 5000

